[server]
headless = true
address = "127.0.0.1"
port = 8501

[theme]
primaryColor = "#2E86C1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5F9"
textColor = "#262730"
font = "sans serif"
